services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    - 3306:3306
    expose:
      - 3306
    volumes:
       - ./script.sql:/docker-entrypoint-initdb.d/script.sql